// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swdqenypcehvobudhszb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3ZHFlbnlwY2Vodm9idWRoc3piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MTY0NjgsImV4cCI6MjA2ODE5MjQ2OH0.PShrD_2ZkwhWRzqZBmvKWYx73rLWAP_1i5IM63lWqeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});